web/modules/custom/par_styleguide/src/Form/StyleguideForm.php
web/themes/custom/par_theme/templates/checkboxes.html.twig
web/themes/custom/par_theme/templates/fieldset.html.twig
web/themes/custom/par_theme/templates/form-element-label.html.twig
web/themes/custom/par_theme/templates/form-element.html.twig
web/themes/custom/par_theme/templates/input--textfield.html.twig
web/themes/custom/par_theme/templates/input.html.twig
web/themes/custom/par_theme/templates/radios.html.twig
web/themes/custom/par_theme/templates/select.html.twig
web/themes/custom/par_theme/templates/textarea.html.twig

Can be seen at http://127.0.0.1:8111/styleguide/forms

Text field, textarea and file upload styled

---

web/modules/custom/par_styleguide/src/Form/StyleguideForm.php

PAR-39: Removed double typed array keys.

---

composer.json
composer.lock
drupal-update.sh
sync/health_check.settings.yml
web/modules/custom/par_forms/modules/par_demo_forms/src/Form/ParDemoThirdForm.php
web/modules/custom/par_forms/src/Entity/ParFormFlow.php
web/modules/custom/par_forms/src/Form/ParBaseForm.php

The method `getAllTempData` gets all the data that has been entered for the flow.
The method `deleteStore` will delete all the data that has been entered for the flow.
The saving and deleting must be handled manually in the submit handler for any form that requires it. As a rule, whenever you save the data to the permanent store you will want to delete the temporary store.
See the par_demo_forms module for a full example.
```
$all_flow_data = $this->getAllTempData();
$data = [
'type' => 'article',
'title' => $all_flow_data['name'],
'uid' => $this->currentUser->id(),
];
$node = \Drupal::entityManager()
->getStorage('node')
->create($data);
// Make sure to only delete the store if the data was correctly saved.
if ($node->save()) {
$this->deleteStore();
}
```

PAR-162: Added method to clear form flow data

---

.bp-config/options.json
.bp-config/php/php.ini.d/gd.ini
README.md
Vagrantfile

Install GD Extension

---

.travis.yml
web/sites/default/settings.php

First attempt to set environment variables on PaaS

Add cf-cli using apt-get

---

dashboard/jobs/production_status.rb
dashboard/widgets/number/number.coffee

Minor change to stop the numbers spinning and to reduce frequency to every 30 seconds in order to reduce spin-induced headaches :)

Reduce frequency and animation of spinning numbers

---

sync/block.block.par_theme_breadcrumbs.yml
sync/block.block.par_theme_content.yml
sync/block.block.par_theme_help.yml
sync/block.block.par_theme_local_actions.yml
sync/block.block.par_theme_local_tasks.yml
sync/block.block.par_theme_messages.yml
sync/block.block.par_theme_page_title.yml
sync/block.block.sitewidehelpdeskmessage.yml
sync/system.logging.yml

this will need to be recreated in the live database to persist this block. the new block should have this content "If you need assistance call the Help Desk 0121 345 1201"

block configuration to introduce the sitewide help desk message

---

sync/block.block.sitewidehelpdeskmessage.yml

Does this make any sense? Or do I have to make another call?

updating UUIDs

---

docker/docker-compose.yml

This version of the docker image contains Paul's latest software dependencies for feature tests.

Use version 8 of web docker web image

---

.travis.yml
tools/dump.py

This is the first step - performing the dump following the deploy.

Postgres dump

---

web/modules/custom/par_data/src/Entity/ParDataPartnership.php
web/modules/custom/par_flow_transition_partnership_details/src/Form/ParFlowTransitionOverviewForm.php

DEV: Correcting contact display.

---

sync/core.entity_view_display.par_data_organisation.business.summary.yml
sync/core.entity_view_display.par_data_organisation.business.title.yml
sync/core.entity_view_display.par_data_partnership.partnership.summary.yml
sync/core.entity_view_display.par_data_partnership.partnership.title.yml
sync/core.entity_view_display.par_data_premises.premises.summary.yml
web/modules/custom/par_data/src/Entity/ParDataPartnership.php
web/modules/custom/par_data_test/par_data_test.module
web/modules/custom/par_flow_transition_partnership_details/src/Form/ParFlowTransitionOverviewForm.php
web/themes/custom/par_theme/templates/address-plain.html.twig

examples. Keeping PR lean to get component updates in as I go along.

Addresses on one line 

---

web/themes/custom/par_theme/templates/address-plain.html.twig

remove unnecessary whitespace in template, separate the postcode.

improve addresses

---

sync/core.entity_view_display.par_data_authority.authority.title.yml
sync/core.entity_view_display.par_data_organisation.coordinator.summary.yml
sync/core.entity_view_display.par_data_regulatory_area.regulatory_area.default.yml
sync/core.entity_view_display.par_data_regulatory_area.regulatory_area.full.yml
sync/core.entity_view_display.par_data_regulatory_area.regulatory_area.summary.yml
sync/core.entity_view_display.par_data_regulatory_area.regulatory_area.title.yml
sync/views.view.par_data_transition_journey_1_step_1.yml
web/modules/custom/par_flow_transition_partnership_details/src/Form/ParFlowTransitionTermsForm.php

Tables and sorting Regulatory Area regressions

---

tests/src/features/PAR189-Edit-Main-PA-Contact-Save-Form-Data.feature
tests/src/features/PAR191-Edit-Second-PA-Contact-Save-Form-Data.feature
tests/src/features/PAR66-Edit-Second-PA-Contact-Create-Form.feature
web/modules/custom/par_flow_transition_business/par_flow_transition_business.routing.yml
web/modules/custom/par_flow_transition_partnership_details/par_flow_transition_partnership_details.routing.yml
web/modules/custom/par_flow_transition_partnership_details/src/Form/ParFlowTransitionTermsForm.php

In this scenario, I have reset some back to `Updating the Primary Authority Register` and will expect this to be changed.

I think the titles need changing for now.

---

web/modules/custom/par_flows/src/Controller/ParBaseController.php
web/modules/custom/par_flows/src/Form/ParBaseForm.php
web/modules/custom/par_flows/src/ParDisplayTrait.php

@kalpaitch whatcha think
@stephenb01 this will be our saviour
@nao360 this may be of interest

Introducing ParDisplayTrait is used for displaying/theming functions.

---

sync/core.extension.yml
sync/views.view.par_data_transition_journey_1_step_1.yml

Keeping this as lean as possible.
Enabling Better Exposed Filters as I know this will be used for everything else to keep it uniform.

PAR-281: Add Status filter to DV Journey 1 Step 1

---

web/modules/custom/par_flow_transition_partnership_details/src/Controller/ParFlowTransitionTaskListController.php

missing labels, titles etc.

---

web/modules/custom/par_flow_transition_business/src/Form/ParFlowTransitionTermsForm.php
web/modules/custom/par_flow_transition_partnership_details/src/Form/ParFlowTransitionTermsForm.php

Removes markup from the PA Officer, Business and Coordinator flows.

Removes "What's changed?" bullet points as requested by RD

---

tests/wdio.BROWSERSTACK.conf.js

Revert browserstack config keys regression

---

web/modules/features/par_welcome_page/par_welcome_page.install

Updates welcome page with copy and styling changes requested by RD

---

sync/views.view.par_data_transition_journey_1_step_1.yml
tests/src/features/DV-transition-journey-5/user-journey-business-manage-addresses-as-pa.feature
tests/src/features/PAO-transition-journey-1/user-journey-change-partnership-detail.feature
tests/src/features/PAO-transition-journey-1/user-journey-inspection-plans.feature
tests/src/features/PAO-transition-journey-1/user-journey-send-invite.feature
web/themes/custom/par_theme/sass/par/_views.scss

Updates partnership dashboard view with copy changes requested by RD.
Updates tests to match new partnership dashboard view title.

Copy changes partnership dashboard

---

composer.json
composer.lock

File: Corrected file download bug

---

manifest.production.yml
manifest.staging.yml

Doubling disk and memory quotas for staging and production.

Increase staging and prod mem and disk

---

web/modules/custom/par_flows/src/ParDisplayTrait.php

show none if field has no data on `renderMarkupField`

---

web/modules/custom/par_flow_transition_business/src/Form/ParFlowTransitionDetailsForm.php
web/modules/custom/par_flow_transition_coordinator/src/Form/ParFlowTransitionDetailsForm.php

- The checkbox for coordinator was appearing below the submit button
when there are no trading names.

Fixed bug on the coordiator detail page.

---

web/themes/custom/par_theme/sass/par.scss

prevent fieldset/legend/table misalignment with display

---

sync/par_flows.par_flow.transition_partnership_details.yml
tests/src/features/DV-transition-journey-5/user-journey-helpdesk-as-primary-authority.feature
tests/src/features/PAO-transition-journey-1/user-journey-primary-authority.feature
web/modules/custom/par_data/src/Entity/ParDataEntity.php
web/modules/custom/par_flow_transition_partnership_details/config/install/par_flows.par_flow.transition_partnership_details.yml
web/modules/custom/par_flow_transition_partnership_details/par_flow_transition_partnership_details.routing.yml
web/modules/custom/par_flow_transition_partnership_details/src/Controller/ParFlowTransitionAdviceListController.php
web/modules/custom/par_flow_transition_partnership_details/src/Form/ParFlowTransitionAdviceForm.php
web/modules/custom/par_flow_transition_partnership_details/src/Form/ParFlowTransitionAdviceUploadForm.php

Provides a new link "Upload a document" to go to the multiple file upload.
It then sends the user straight to the classify documentation screen.

PAR-16: Upload advice documentation

---

sync/config_split.config_split.dev_config.yml
sync/core.extension.yml
sync/par_flows.par_flow.partnership_authority.yml
sync/par_flows.par_flow.transition_partnership_details.yml
web/modules/features/par_partnership_flows/config/install/par_flows.par_flow.partnership_authority.yml
web/modules/features/par_partnership_flows/par_partnership_flows.routing.yml
web/modules/features/par_partnership_flows/src/Controller/ParPartnershipFlowsAdviceListController.php
web/modules/features/par_partnership_flows/src/Controller/ParPartnershipFlowsInspectionPlanListController.php
web/modules/features/par_partnership_flows/src/Form/ParPartnershipFlowsAuthorityContactForm.php
web/modules/features/par_partnership_flows/src/ParPartnershipFlowsTrait.php

This is still in development so some code has been commented out.

Authority Flow

---

sync-beta/.htaccess
sync-beta/login_destination.destination.welcome_reminder.yml
sync/config_split.config_split.beta_config.yml
web/sites/default/settings.php

All you need to do to enable the beta flows is enable beta config in your local settings file:
`$config['config_split.config_split.beta_config']['status'] = FALSE;`

PAR-560: Added config split for beta.

---

composer.json
composer.lock
sync/core.extension.yml
sync/google_analytics.settings.yml

The analytics JS snippet shows up in script tags within the head tags within the html tags, so clearly it works.

Adds google analytics module and configuration

---

sync/views.view.par_data_transition_journey_1_step_1.yml
tests/src/features/DV-transition-journey-2/user-journey-business-user.feature

Fix for the partnership dashboard.

---

sync/user.role.par_business.yml
sync/user.role.par_coordinator.yml
sync/user.role.par_enforcement.yml
sync/user.role.par_organisation.yml
sync/views.view.partnership_search.yml
web/modules/custom/par_components/par_components.info.yml
web/modules/custom/par_data/src/Entity/ParDataEnforcementAction.php
web/modules/custom/par_data/src/Entity/ParDataInspectionPlan.php
web/modules/custom/par_data/src/Entity/ParDataPartnership.php
web/modules/custom/par_flow_transition_business/par_flow_transition_business.info.yml
web/modules/custom/par_flow_transition_coordinator/par_flow_transition_coordinator.info.yml
web/modules/custom/par_flow_transition_partnership_details/par_flow_transition_partnership_details.info.yml
web/modules/custom/par_migration/par_migration.info.yml
web/modules/custom/par_roles/par_roles.permissions.yml
web/modules/features/par_migration_scripts/par_migration_scripts.info.yml

Also contains depreciated tags for code and config not wanted any more.

PAR-430: Initial setup of partnership search page.

---

cf/push.sh

This is an update of the deploy script that does some useful things:
1) Prompts for Cloud Foundry credentials - possibly a pain, but worse is if your login gets timed out halfway through a deploy because you logged in a while back.
2) Prompts for Vault authentication, if needed
3) Hardcodes the Vault location
4) More checks and stops on failures

Bulletproof the deployment script

---

.bp-config/httpd/httpd.conf

If I create it you can then merge more easily :)

PAR-570: Disable TRACE

---

web/modules/custom/par_data/par_data.install
web/modules/custom/par_data/src/Entity/ParDataAdvice.php
web/modules/custom/par_data/src/Entity/ParDataAuthority.php
web/modules/custom/par_data/src/Entity/ParDataCoordinatedBusiness.php
web/modules/custom/par_data/src/Entity/ParDataEnforcementAction.php
web/modules/custom/par_data/src/Entity/ParDataEnforcementNotice.php
web/modules/custom/par_data/src/Entity/ParDataInspectionPlan.php
web/modules/custom/par_data/src/Entity/ParDataLegalEntity.php
web/modules/custom/par_data/src/Entity/ParDataOrganisation.php
web/modules/custom/par_data/src/Entity/ParDataPartnership.php
web/modules/custom/par_data/src/Entity/ParDataPerson.php
web/modules/custom/par_data/src/Entity/ParDataPremises.php
web/modules/custom/par_data/src/Entity/ParDataRegulatoryFunction.php
web/modules/custom/par_data/src/Entity/ParDataSicCode.php

Introduce view display option view weights.

---

sync/views.view.partnership_search.yml
web/modules/features/par_dashboards/src/Controller/ParDashboardsDashboardController.php

This PR removes an old dashboard view display no longer being used as well as updating the dashboard controller to ref the correct route for the required view display.

Enforcment Dashboard update

---

composer.json
composer.lock
patches/password_strength_dictionary.patch
sync/core.extension.yml
sync/password_policy.password_policy.default.yml
sync/password_strength.settings.yml

I have installed the module plugin "password_strength" for the module "password_policy". I removed all the matchers except for the dictionary lookup matcher. I created a patch which changes the message to be specific about the dictionary matching.

Password strength

---

sync/par_flows.par_flow.partnership_authority.yml
web/modules/features/par_partnership_flows/config/install/par_flows.par_flow.partnership_authority.yml
web/modules/features/par_partnership_flows/par_partnership_flows.routing.yml
web/modules/features/par_partnership_flows/src/Form/ParPartnershipFlowsAuthorityDetailsForm.php
web/modules/features/par_partnership_flows/src/Form/ParPartnershipFlowsContactForm.php
web/modules/features/par_partnership_flows/src/Form/ParPartnershipFlowsContactSuggestionForm.php

An improvement to the contact search, further refactoring necessary, but best to keep these forms up to date with permissions

PAR-590 WIP

---

sync/core.entity_view_display.par_data_legal_entity.legal_entity.summary.yml
web/modules/features/par_data_config/config/install/core.entity_view_display.par_data_legal_entity.legal_entity.summary.yml

fix regression on this summary view

---

web/modules/custom/par_data/src/Entity/ParDataPerson.php

PAR-649: Added email validation to people.

---

sync/core.entity_view_display.par_data_organisation.organisation.default.yml
sync/core.entity_view_display.par_data_organisation.organisation.full.yml
sync/core.entity_view_display.par_data_partnership.partnership.default.yml
web/modules/custom/par_data/src/ParDataManager.php
web/modules/custom/par_flows/src/ParDisplayTrait.php
web/modules/features/par_data_config/config/install/core.entity_view_display.par_data_organisation.organisation.default.yml
web/modules/features/par_data_config/config/install/core.entity_view_display.par_data_organisation.organisation.full.yml
web/modules/features/par_data_config/config/install/core.entity_view_display.par_data_partnership.partnership.default.yml

PAR-648: Updated rendering of individual fields.

---

sync/par_flows.par_flow.raise_enforcement.yml
web/modules/features/par_enforcement_flows/config/install/par_flows.par_flow.raise_enforcement.yml

Updates for enforcement flow links required for PAR-418.

enforcement flow raise notice link fix

---

web/modules/features/par_enforcement_flows/src/Controller/ParEnforcementFlowsPartnershipPageController.php

PAR-650: Remove enforcement actions link.

---

web/modules/features/par_enforcement_flows/src/Form/ParEnforcementRaiseNoticeForm.php

This provides the base form for enforcement notifications. There is more functionality for this form which I have added to another branch PR to follow.

enforcment notification base form

---

web/modules/features/par_enforcement_flows/src/Form/ParEnforcementAddActionForm.php

PAR-419 base form for enforcement notification actions

---

sync/par_flows.par_flow.partnership_application.yml
web/modules/custom/par_data_test/par_data_test.module
web/modules/features/par_partnership_flows/config/install/par_flows.par_flow.partnership_application.yml
web/modules/features/par_partnership_flows/par_partnership_flows.routing.yml
web/modules/features/par_partnership_flows/src/Form/ParPartnershipFlowsApplicationAddOrganisationForm.php
web/modules/features/par_partnership_flows/src/Form/ParPartnershipFlowsApplicationAuthorityChecklistForm.php
web/modules/features/par_partnership_flows/src/Form/ParPartnershipFlowsApplicationDetailsForm.php
web/modules/features/par_partnership_flows/src/Form/ParPartnershipFlowsApplicationOrganisationSearchForm.php
web/modules/features/par_partnership_flows/src/Form/ParPartnershipFlowsApplicationTypeForm.php
web/modules/features/par_partnership_flows/src/Form/ParPartnershipFlowsOrganisationSuggestionForm.php
web/modules/features/par_partnership_flows/src/ParPartnershipFlowsTrait.php

Start of the partnership application journey.

PAR-630: Built out some of the screens, routes (tbc) and flow.

---

web/modules/custom/par_data/par_data.install
web/modules/custom/par_data/src/Entity/ParDataOrganisation.php
web/modules/custom/par_roles/par_roles.module

Do not merge yet. Must be merged only once final migration has been completed.

PAR-301: Added entity update scripts for users and organisations. DO NOT MERGE

---

web/modules/custom/par_flows/src/Form/ParBaseForm.php
web/modules/features/par_partnership_flows/src/Form/ParPartnershipFlowsApplicationAuthorityChecklistForm.php

Updated messages back to something like wot @stephenb01 had.

PAR-635: Updated messages.

---

web/modules/features/par_partnership_flows/par_partnership_flows.routing.yml
web/modules/features/par_partnership_flows/src/Form/ParPartnershipFlowsContactForm.php

Removing comments which don't add much value (one is actually not even accurate)
Changing route.

Change route to /partnership/apply/{id}/review

---

sync/views.view.public_register.yml
web/modules/custom/par_roles/par_roles.permissions.yml

PAR-426: Added public register.

---

web/modules/custom/par_flows/src/ParDisplayTrait.php

Well it turns out paginating plain results wasn't so complicated after all, and I think this is probably the best result we will get for now.

Multipass: Multi field paginated.

---

sync/views.view.helpdesk_dashboard.yml
web/modules/custom/par_roles/par_roles.permissions.yml

Helpdesk link displays in user menu for users that are able to access it:

PAR-595: Updated helpdesk page and permissions.

---

web/modules/features/par_enforcement_flows/src/Form/ParEnforcementSubmitNoticeForm.php

Resolves the build failing issues

---

web/modules/features/par_enforcement_flows/src/Form/ParEnforcementRaiseNoticeDetailsForm.php

Store enforcement prim authority in the entity ref field.

adding missing enforcement notification data

---

sync/field.field.par_data_authority.authority.field_premises.yml
sync/field.field.par_data_organisation.organisation.field_premises.yml
sync/par_data.par_data_advice_type.advice.yml
sync/par_data.par_data_enforcement_action_type.enforcement_action.yml
sync/par_data.par_data_enforcement_notice_type.enforcement_notice.yml
sync/par_data.par_data_inspection_plan_type.inspection_plan.yml
sync/par_data.par_data_sic_code_type.sic_code.yml
sync/views.view.partnership_search.yml
web/modules/custom/par_flows/src/ParDisplayTrait.php
web/modules/features/par_data_config/config/install/field.field.par_data_authority.authority.field_premises.yml
web/modules/features/par_data_config/config/install/field.field.par_data_organisation.organisation.field_premises.yml
web/modules/features/par_data_config/config/install/par_data.par_data_advice_type.advice.yml
web/modules/features/par_data_config/config/install/par_data.par_data_enforcement_action_type.enforcement_action.yml
web/modules/features/par_data_config/config/install/par_data.par_data_enforcement_notice_type.enforcement_notice.yml
web/modules/features/par_data_config/config/install/par_data.par_data_inspection_plan_type.inspection_plan.yml
web/modules/features/par_data_config/config/install/par_data.par_data_organisation_type.business.yml
web/modules/features/par_data_config/config/install/par_data.par_data_premises_type.premises.yml
web/modules/features/par_data_config/config/install/par_data.par_data_sic_code_type.sic_code.yml
web/modules/features/par_partnership_flows/src/Form/ParPartnershipFlowsDetailsForm.php

BUG: Changed number of legal entities on partnership search

---

web/modules/features/par_rd_help_desk_flows/config/install/par_flows.par_flow.approve_partnership.yml
web/modules/features/par_rd_help_desk_flows/par_rd_help_desk_flows.features.yml
web/modules/features/par_rd_help_desk_flows/par_rd_help_desk_flows.info.yml
web/modules/features/par_rd_help_desk_flows/par_rd_help_desk_flows.routing.yml
web/modules/features/par_rd_help_desk_flows/src/Form/ParRdHelpDeskApproveForm.php
web/modules/features/par_rd_help_desk_flows/src/Form/ParRdHelpDeskConfirmForm.php

This module provides all the functionality required to enable RD help desk users to approve a partnership.

feture module required to provide business logic for approving partneships

---

sync/field.field.par_data_authority.authority.field_allowed_regulatory_fn.yml
sync/field.field.par_data_authority.authority.field_regulatory_function.yml
sync/field.field.par_data_enforcement_notice.enforcement_notice.field_enforcement_action.yml
sync/field.field.par_data_organisation.organisation.field_coordinated_businesses.yml
sync/par_flows.par_flow.partnership_coordinated.yml
web/modules/features/par_partnership_flows/config/install/par_flows.par_flow.partnership_coordinated.yml

As we are not using the *Members* section wasn't sure if I should remove the routes from the yml file and also the members section.

PAR-697: Fixed flow for coordinator journey.

---

web/modules/features/par_partnership_flows/src/Form/ParPartnershipFlowsApplicationTypeForm.php
web/modules/features/par_partnership_flows/src/Form/ParPartnershipFlowsAuthoritySuggestionForm.php

- The authority selection page.
- The partnership type page.

PAR-698: Added validation to:

---

web/themes/custom/par_theme/templates/form-element.html.twig

Please can we double check this is needed before we get this in? Let's revisit later @nao360

remove checkbox from fields excluded from form-group-error

---

sync/core.entity_form_display.par_data_enforcement_notice.enforcement_notice.default.yml
sync/core.entity_view_display.par_data_enforcement_notice.enforcement_notice.default.yml
sync/field.field.par_data_enforcement_notice.enforcement_notice.field_organisation.yml
sync/field.storage.par_data_enforcement_notice.field_organisation.yml
sync/par_flows.par_flow.raise_enforcement.yml
web/modules/custom/par_data/src/ParDataManager.php
web/modules/custom/par_data/tests/src/Kernel/ParDataTestBase.php
web/modules/features/par_data_config/config/install/core.entity_form_display.par_data_enforcement_notice.enforcement_notice.default.yml
web/modules/features/par_data_config/config/install/core.entity_view_display.par_data_enforcement_notice.enforcement_notice.default.yml
web/modules/features/par_data_config/config/install/field.field.par_data_enforcement_notice.enforcement_notice.field_organisation.yml
web/modules/features/par_data_config/config/install/field.storage.par_data_enforcement_notice.field_organisation.yml
web/modules/features/par_enforcement_flows/config/install/par_flows.par_flow.raise_enforcement.yml
web/modules/features/par_enforcement_flows/par_enforcement_flows.routing.yml
web/modules/features/par_enforcement_flows/src/Controller/ParEnforcementFlowsPartnershipPageController.php
web/modules/features/par_enforcement_flows/src/Form/ParEnforcementRaiseNoticeDetailsForm.php
web/modules/features/par_enforcement_flows/src/Form/ParEnforcementRaiseNoticeForm.php
web/modules/features/par_enforcement_flows/src/Form/ParPartnershipFlowsEnforceOrganisationForm.php
web/modules/features/par_rd_help_desk_flows/src/Form/ParRdHelpDeskApproveConfirmForm.php

This PR allows enforcements to be made against coordinated partnerships:

Enforcements: Added organisation to the enforcement notice.

---

web/modules/features/par_partnership_flows/src/Controller/ParPartnershipFlowsAdviceListController.php
web/modules/features/par_partnership_flows/src/Form/ParPartnershipFlowsAdviceForm.php

Advice Form… Repair Regulatory functions, rectify foreach() notices, refactor slightly.

---

web/modules/features/par_enforcement_flows/src/Form/ParEnforcementRaiseNoticeForm.php
web/modules/features/par_enforcement_flows/src/Form/ParPartnershipFlowsEnforceOrganisationForm.php

PAR-709: Fixed error message on enforcement notice.

---

sync/par_flows.par_flow.partnership_authority.yml
web/modules/features/par_partnership_flows/config/install/par_flows.par_flow.partnership_authority.yml
web/modules/features/par_partnership_flows/src/Form/ParPartnershipFlowsApplicationConfirmationForm.php
web/modules/features/par_partnership_flows/src/Form/ParPartnershipFlowsDetailsForm.php

`partnership_status` is also changed.

Authority/Organisation Terms Checkboxes now save to the partnership.

---

web/modules/custom/par_actions/src/Plugin/Action/ParBulkInviteAction.php

It works and it doesn't affect anything else so merging.

Bulk invite update.

---

web/modules/features/par_enforcement_flows/src/Form/ParEnforcementRaiseNoticeDetailsForm.php

add notice_date to display "received date" in view.

---

web/modules/custom/par_data/src/Entity/ParDataOrganisation.php

Change label to repair the "error size" issue

---

web/modules/custom/par_data/src/Entity/ParDataType.php

Enable enforcement actions to be able to change state without validation triggering in every instance.

 enforcement actions fix

---

web/modules/features/par_enforcement_flows/par_enforcement_flows.routing.yml

Remove old enforcement flow routes no longer used due to design updates during development.

Code clean-up

---

sync/views.view.par_user_enforcements.yml

those without the permission see this

Enforcement Notice view restricted to those with 'access par_data_enforcement_notice entities' permission.

---

web/modules/features/par_dashboards/src/Controller/ParDashboardsDashboardController.php

Add help text "Search for active partnerships…"

---

web/modules/features/par_partnership_flows/src/Form/ParPartnershipFlowsApplicationConfirmationForm.php

PAR-676 missing both addresses

---

sync/par_flows.par_flow.partnership_coordinated.yml
sync/par_flows.par_flow.partnership_direct.yml
web/modules/features/par_partnership_flows/config/install/par_flows.par_flow.partnership_coordinated.yml
web/modules/features/par_partnership_flows/config/install/par_flows.par_flow.partnership_direct.yml

this rectifies saving this as a PAR organisation user.

this should be a save step so the tickbox saves

---

sync/core.entity_view_display.par_data_legal_entity.legal_entity.summary.yml
web/modules/features/par_data_config/config/install/core.entity_view_display.par_data_legal_entity.legal_entity.summary.yml

Reordering the fields for legal entities in the partnership detail view:

PAR-753: Reorder the legal entity fields in the summary view.

---

web/modules/custom/par_data/src/Entity/ParDataEnforcementAction.php
web/modules/features/par_enforcement_flows/par_enforcement_flows.routing.yml
web/modules/features/par_enforcement_flows/src/Form/ParEnforcementApproveNoticeForm.php
web/modules/features/par_enforcement_flows/src/Form/ParEnforcementConfirmNoticeForm.php
web/modules/features/par_enforcement_flows/src/Form/ParEnforcementReferredAuthorityForm.php

This PR contains the completed and tested business logic for updating enforcement notices however a new ticket is required for the referral of actions and a code clean up is required to update/remove some of the logic around states in the confirm notice form.
We need to clarify some of the business rules around referrals as well.  
PAR-791, PaR-814, PAR-816, PAR-831

PAR-791, PAR-814, PAR-816, PAR-831

---

.gitignore
.travis.yml
tests/src/features/5-user-journey-coordinator-user-update-partnership.feature
tests/src/features/6-user-journey-partnership-update-primary-authority.feature
tests/src/features/7-user-journey-organisation-user-update-partnership.feature
tests/src/features/8-user-journey-primary-authority-new-coordinated-partnership.feature

have fixed the version of Google Chrome to the one that webdriver works with.
have also made sure some of the tests don't try approve partnerships more than once.
travis now only tries once to pass the tests to save wasted time.

Tests now pass
