- tests/pa11y/README.md
- tests/pa11y/docker/README.md
- tests/src/features/TASK138-Pagination.feature
- tests/src/support/check/checkContainsText.js
The fixes the current failing tests on master branch (now the pagination test does a partial check, instead of relying on total number of pages remaining the same)
> Added code to check for partial text string in elements

- gulpfile.js
this will copy the necessary images in this folder to make the GDS footer show the crown and OGL emblem.
> copy assets into /assets/vendor/images/

- web/themes/custom/par_theme/templates/input--password.html.twig
improve the login form by simply applying a CSS class
> form password fields should also have the form-control attribute.

- composer.json
- composer.lock
- patches/README.md
- patches/drush-sqldump-postgres95.patch
Implementing a patch from https://github.com/drush-ops/drush/pull/2282/commits/145dd25e5d6b037e59c0a457d42688a2ccc74ee0 to fix compatibility with Postgres 9.5+.
Updating composer.* files for later versions.
> Patch Drush for compatibility for pg_dump w/ Postgres 9.5

- docker/setup.sh
I often run into problems with xmlsitemap and watchdog PDOexceptions saying table already exists in database without having a clean postgres database.
> remove whitespace & drush sql-drop before sql-cli /sync

- web/themes/custom/par_theme/templates/input--email.html.twig
email input fields need the form-control class.
> as per all input--xx.html.twig templates, email needs the wrapper

- sync/views.view.par_data_transition_journey_1_step_1.yml
- tests/src/features/current-sprint/PAR179-Capture-Partnership-Entity-Section-States.feature
- tests/src/features/user-journey-change-partnership-detail.feature
- tests/src/features/user-journey-documentation.feature
- tests/src/features/user-journey-inspection-plans.feature
- tests/src/features/user-journey-send-invite.feature
Because we use this view across Business and PA, the title should not say List of Partnerships for a Primary Authority…
> Update View to say 'List of Partnerships' and update the tests

- web/themes/custom/par_theme/sass/par.scss
- web/themes/custom/par_theme/templates/page.html.twig
Replaces the 'green box' PAR logo with a textual heading as requested by RD. SCSS updated accordingly.
> Replace par logo

- web/modules/custom/par_flow_transition_partnership_details/src/Controller/ParFlowTransitionTaskListController.php
Adds .heading-medium class to the h2 tag surrounding the organisation name as required by UX.
> Fixes organisation name heading display

- tests/src/features/DV-transition-journey-5/user-journey-business-manage-addresses-as-pa.feature
- tests/src/features/PAO-transition-journey-1/user-journey-change-partnership-detail.feature
- tests/src/features/PAO-transition-journey-1/user-journey-inspection-plans.feature
- tests/src/features/PAO-transition-journey-1/user-journey-send-invite.feature
- web/modules/custom/par_flow_transition_partnership_details/src/Controller/ParFlowTransitionTaskListController.php
Updates the 'Go back to your partnerships' button text on the Transition task list to read, 'Save and continue' as per UX requirements.
Updates related cucumbers.
> Change task list button text

- web/modules/custom/par_flow_transition_partnership_details/src/Controller/ParFlowTransitionTaskListController.php
Somehow this got undone - redone now.
> Uses organisation_name instead of name to display organisation name

- web/modules/custom/par_flow_transition_partnership_details/par_flow_transition_partnership_details.routing.yml
- web/modules/custom/par_flow_transition_partnership_details/src/Form/ParFlowTransitionOverviewForm.php
Copy correction - viewing/confirming partnership details
URL: /dv/primary-authority-partnerships/4/details
Page title should read, 'Updating the Primary Authority Register'
Checkbox options should read:
I confirm that the partnership information above is correct
A written summary of the partnership arrangements has been agreed with the business
> Partnership details copy changes 21/07

- cf/push.sh
- cf/update-domain-production.sh
Force user to enter vault unseal key even if vault is already unsealed. Prompt for environment name and build version rather than pass them as command line arguments.
> Deployment script prompting for most variables

- .travis.yml
This PR reinstates the `rm -rf node_modules`, having figured out that this directory is actually cached. we should use `npm update` in the future to invalidate this directory cache.
> Trying to rectify issues with chromedriver

- sync/google_analytics.settings.yml
Tracks all users except Administrator and RD Help Desk users. Removes URL tracking for paths in /admin/* and /dv/rd-helpdesk/*
Configuration screenshots as follows:
> Updates GA configuration to correct configuration

- composer.json
- patches/drush-sql-dump-no-extra-fix.patch
The problem was that when Drush was using the Postgres tools to get a list of tables, it was also passing in all the "extra" params from the drush aliases - thinking it was a good idea because it was all part of the "sql-dump" command. This caused the table list exec to fail and caused the remained of the logic to go wonky as well. This patch fixes it by explicitly telling one of the functions not to add the extra stuff, when asked not to do so, such as when it is being called for a table list.
> Drush "no extra" fix

- web/modules/custom/par_flows/src/Form/ParBaseForm.php
An option for previous/back and flow cancel.
example usage
`
$form['actions']['cancel'] = [
'#type' => 'submit',
'#name' => 'cancel',
'#value' => $this->t('Cancel'),
'#submit' => ['::cancelForm'],
'#limit_validation_errors' => [],
'#attributes' => [
'class' => ['btn-link']
],
];
`
> Cancel all flow forms and cancel flow form submit handlers.

- web/modules/custom/par_data_test/par_data_test.module
@chris-moreton @stemount I've added a test admin user for @jaffamonkey's testing.
What has become apparent in doing so is that we should only ever use the test data with a sanitized database. Otherwise anyone will be able to log in just by looking through our repo.
> Test: Added admin test user.

- web/modules/custom/par_data/src/ParDataManager.php
- web/modules/custom/par_data/src/ParDataStorage.php
The intention of this PR is to fix the bug where _New partnerships aren't added to membership lookup cache_.
> PAR-817 Re-cache the related entities when saving an entity

- sync/views.view.helpdesk_dashboard.yml
- web/modules/custom/par_flows/src/Form/ParBaseForm.php
- web/modules/features/par_rd_help_desk_flows/par_rd_help_desk_flows.routing.yml
- web/modules/features/par_rd_help_desk_flows/src/Form/ParRdHelpDeskApproveConfirmForm.php
update the view so that it works properly with the PAR Flow Link
implement an access callback in ParBaseForm for use in other areas of the site
add the rule and access callback to approve partnership route
_Active partnerships show N/A_
_Applications show approve link_
> implementation of an access callback for Helpdesk Approve Partnership.

- sync/par_data.par_data_enforcement_action_type.enforcement_action.yml
- sync/par_flows.par_flow.approve_enforcement.yml
- sync/par_flows.par_flow.send_enforcement.yml
- sync/views.view.par_user_enforcements.yml
- web/modules/custom/par_data/src/Entity/ParDataEnforcementAction.php
- web/modules/custom/par_data/src/Entity/ParDataEnforcementNotice.php
- web/modules/custom/par_flows/src/Controller/ParBaseController.php
- web/modules/features/par_data_config/config/install/par_data.par_data_enforcement_action_type.enforcement_action.yml
- web/modules/features/par_data_config/par_data_config.info.yml
- web/modules/features/par_enforcement_flows/config/install/par_flows.par_flow.approve_enforcement.yml
- web/modules/features/par_enforcement_flows/par_enforcement_flows.routing.yml
- web/modules/features/par_enforcement_flows/src/Controller/ParEnforcementFlowsCompletedEnforcementController.php
- web/modules/features/par_enforcement_flows/src/Form/ParEnforcementAddActionForm.php
- web/modules/features/par_enforcement_flows/src/Form/ParEnforcementApproveNoticeForm.php
- web/modules/features/par_enforcement_flows/src/Form/ParEnforcementConfirmNoticeForm.php
This PR adds custom access control to ensure the correct users can/cannot access versions of the notification actions dictated by custom business logic.
Custom flow link added to enforcement notifications view to control the displaying of actions that need to be reviewed or acted on depending on the logged in user role (enforcement officer / primary authority user).
Review controller added to display the resulting acted upon enforcement notification.
> PAR-421 additional features for enforcement notifications
